[2022-02-19 00:32:04,282] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 00:32:04,296] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 00:32:04,296] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 00:32:04,296] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-19 00:32:04,296] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 00:32:04,310] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): bash_task> on 2022-02-19 00:00:00+00:00
[2022-02-19 00:32:04,314] {standard_task_runner.py:52} INFO - Started process 216 to run task
[2022-02-19 00:32:04,317] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'configuration_dag', 'bash_task', 'manual__2022-02-19T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/configuration_dag.py', '--cfg-path', '/tmp/tmp7jnflj_y', '--error-file', '/tmp/tmpmk4l85en']
[2022-02-19 00:32:04,317] {standard_task_runner.py:77} INFO - Job 4: Subtask bash_task
[2022-02-19 00:32:04,375] {logging_mixin.py:109} INFO - Running <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [running]> on host 2e85b2b3b082
[2022-02-19 00:32:04,432] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=configuration_dag
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T00:00:00+00:00
[2022-02-19 00:32:04,433] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 00:32:04,434] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/usr/local/spark/configure.sh ']
[2022-02-19 00:32:04,443] {subprocess.py:85} INFO - Output:
[2022-02-19 00:32:07,552] {subprocess.py:89} INFO - A connection with `conn_id`=spark_default already exists.
[2022-02-19 00:32:11,453] {subprocess.py:89} INFO - [[34m2022-02-19 00:32:11,453[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 00:32:11,460] {subprocess.py:89} INFO - A connection with `conn_id`=minio_default already exists.
[2022-02-19 00:32:14,783] {subprocess.py:89} INFO - [[34m2022-02-19 00:32:14,783[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 00:32:14,789] {subprocess.py:89} INFO - A connection with `conn_id`=cassandra_default already exists.
[2022-02-19 00:32:16,524] {subprocess.py:89} INFO - Installed kernelspec python3 in /home/***/.local/share/jupyter/kernels/python3
[2022-02-19 00:32:16,628] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-19 00:32:16,653] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=configuration_dag, task_id=bash_task, execution_date=20220219T000000, start_date=20220219T003204, end_date=20220219T003216
[2022-02-19 00:32:16,702] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 00:32:16,731] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-19 01:36:59,087] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 01:36:59,099] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 01:36:59,100] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 01:36:59,100] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-19 01:36:59,100] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 01:36:59,114] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): bash_task> on 2022-02-19 00:00:00+00:00
[2022-02-19 01:36:59,119] {standard_task_runner.py:52} INFO - Started process 732 to run task
[2022-02-19 01:36:59,121] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'configuration_dag', 'bash_task', 'manual__2022-02-19T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/configuration_dag.py', '--cfg-path', '/tmp/tmpuj96eajy', '--error-file', '/tmp/tmpifvnwirj']
[2022-02-19 01:36:59,122] {standard_task_runner.py:77} INFO - Job 4: Subtask bash_task
[2022-02-19 01:36:59,179] {logging_mixin.py:109} INFO - Running <TaskInstance: configuration_dag.bash_task manual__2022-02-19T00:00:00+00:00 [running]> on host 0b7e9ef53975
[2022-02-19 01:36:59,233] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=configuration_dag
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T00:00:00+00:00
[2022-02-19 01:36:59,234] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 01:36:59,235] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/usr/local/spark/configure.sh ']
[2022-02-19 01:36:59,244] {subprocess.py:85} INFO - Output:
[2022-02-19 01:37:02,911] {subprocess.py:89} INFO - A connection with `conn_id`=spark_default already exists.
[2022-02-19 01:37:06,407] {subprocess.py:89} INFO - [[34m2022-02-19 01:37:06,407[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 01:37:06,414] {subprocess.py:89} INFO - A connection with `conn_id`=minio_default already exists.
[2022-02-19 01:37:09,598] {subprocess.py:89} INFO - [[34m2022-02-19 01:37:09,598[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2022-02-19 01:37:09,605] {subprocess.py:89} INFO - A connection with `conn_id`=cassandra_default already exists.
[2022-02-19 01:37:11,871] {subprocess.py:89} INFO - Installed kernelspec python3 in /home/***/.local/share/jupyter/kernels/python3
[2022-02-19 01:37:11,984] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-19 01:37:12,013] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=configuration_dag, task_id=bash_task, execution_date=20220219T000000, start_date=20220219T013659, end_date=20220219T013712
[2022-02-19 01:37:12,073] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 01:37:12,111] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
