[2022-02-19 16:58:28,787] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cassandra_create_test_database_dag.create_table scheduled__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 16:58:28,799] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: cassandra_create_test_database_dag.create_table scheduled__2022-02-19T00:00:00+00:00 [queued]>
[2022-02-19 16:58:28,799] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 16:58:28,799] {taskinstance.py:1239} INFO - Starting attempt 7 of 8
[2022-02-19 16:58:28,800] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 16:58:28,811] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): create_table> on 2022-02-19 00:00:00+00:00
[2022-02-19 16:58:28,816] {standard_task_runner.py:52} INFO - Started process 1308 to run task
[2022-02-19 16:58:28,819] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cassandra_create_test_database_dag', 'create_table', 'scheduled__2022-02-19T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/cassandra_create_test_database_dag.py', '--cfg-path', '/tmp/tmpwe92dauh', '--error-file', '/tmp/tmphibmrsr9']
[2022-02-19 16:58:28,820] {standard_task_runner.py:77} INFO - Job 63: Subtask create_table
[2022-02-19 16:58:28,867] {logging_mixin.py:109} INFO - Running <TaskInstance: cassandra_create_test_database_dag.create_table scheduled__2022-02-19T00:00:00+00:00 [running]> on host ff4bf3af9cad
[2022-02-19 16:58:28,914] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cassandra_create_test_database_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-19T00:00:00+00:00
[2022-02-19 16:58:28,923] {base.py:79} INFO - Using connection to: id: ***_default. Host: 172.20.0.11, Port: 9042, Schema: None, Login: ***, Password: ***, extra: {}
[2022-02-19 16:58:28,924] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/apache/***/hooks/***.py:123: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2022-02-19 16:58:28,927] {cassandra.py:131} WARNING - Downgrading core protocol version from 66 to 65 for 172.20.0.11:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/***/cluster.html#***.cluster.Cluster.protocol_version
[2022-02-19 16:58:28,928] {cassandra.py:131} WARNING - Downgrading core protocol version from 65 to 5 for 172.20.0.11:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/***/cluster.html#***.cluster.Cluster.protocol_version
[2022-02-19 16:58:28,929] {libevreactor.py:370} ERROR - Closing connection <LibevConnection(139859074599952) 172.20.0.11:9042> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
[2022-02-19 16:58:28,929] {cassandra.py:131} WARNING - Downgrading core protocol version from 5 to 4 for 172.20.0.11:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/***/cluster.html#***.cluster.Cluster.protocol_version
[2022-02-19 16:58:29,144] {cassandra_create_test_database_dag.py:47} INFO - >>>>>>>>>>> Executed: Keyspace and Tables are created
[2022-02-19 16:58:29,144] {python.py:175} INFO - Done. Returned value was: None
[2022-02-19 16:58:29,157] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=***_create_test_database_dag, task_id=create_table, execution_date=20220219T000000, start_date=20220219T165828, end_date=20220219T165829
[2022-02-19 16:58:29,191] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 16:58:29,221] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
