[2022-02-22 02:16:29,942] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-book-count.spark_job manual__2022-02-22T02:16:28.078887+00:00 [queued]>
[2022-02-22 02:16:29,957] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-book-count.spark_job manual__2022-02-22T02:16:28.078887+00:00 [queued]>
[2022-02-22 02:16:29,958] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-22 02:16:29,958] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-22 02:16:29,958] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-22 02:16:29,973] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2022-02-22 02:16:28.078887+00:00
[2022-02-22 02:16:29,977] {standard_task_runner.py:52} INFO - Started process 426 to run task
[2022-02-22 02:16:29,980] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-book-count', 'spark_job', 'manual__2022-02-22T02:16:28.078887+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/spark-dag.py', '--cfg-path', '/tmp/tmp22tmxhqx', '--error-file', '/tmp/tmpv2dc6nd_']
[2022-02-22 02:16:29,981] {standard_task_runner.py:77} INFO - Job 2: Subtask spark_job
[2022-02-22 02:16:30,030] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-book-count.spark_job manual__2022-02-22T02:16:28.078887+00:00 [running]> on host c457bd7a09a1
[2022-02-22 02:16:30,081] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-book-count
AIRFLOW_CTX_TASK_ID=spark_job
AIRFLOW_CTX_EXECUTION_DATE=2022-02-22T02:16:28.078887+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-22T02:16:28.078887+00:00
[2022-02-22 02:16:30,082] {base.py:79} INFO - Using connection to: id: spark_default. Host: 172.20.0.9, Port: 7077, Schema: , Login: None, Password: None, extra: {}
[2022-02-22 02:16:30,084] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master 172.20.0.9:7077 --conf spark.master=spark://spark:7077 --name Spark book count --verbose /usr/local/spark/app/spark-book-count.py /usr/local/spark/data/book.txt
[2022-02-22 02:16:31,930] {spark_submit.py:488} INFO - Using properties file: null
[2022-02-22 02:16:32,046] {spark_submit.py:488} INFO - WARNING: An illegal reflective access operation has occurred
[2022-02-22 02:16:32,046] {spark_submit.py:488} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-02-22 02:16:32,046] {spark_submit.py:488} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-02-22 02:16:32,047] {spark_submit.py:488} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-02-22 02:16:32,047] {spark_submit.py:488} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-02-22 02:16:32,127] {spark_submit.py:488} INFO - Parsed arguments:
[2022-02-22 02:16:32,127] {spark_submit.py:488} INFO - master                  172.20.0.9:7077
[2022-02-22 02:16:32,127] {spark_submit.py:488} INFO - deployMode              null
[2022-02-22 02:16:32,127] {spark_submit.py:488} INFO - executorMemory          null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - executorCores           null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - totalExecutorCores      null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - propertiesFile          null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - driverMemory            null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - driverCores             null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - driverExtraClassPath    null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - driverExtraLibraryPath  null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - driverExtraJavaOptions  null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - supervise               false
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - queue                   null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - numExecutors            null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - files                   null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - pyFiles                 null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - archives                null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - mainClass               null
[2022-02-22 02:16:32,128] {spark_submit.py:488} INFO - primaryResource         file:/usr/local/spark/app/spark-book-count.py
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - name                    Spark book count
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - childArgs               [/usr/local/spark/data/book.txt]
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - jars                    null
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - packages                null
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - packagesExclusions      null
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - repositories            null
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - verbose                 true
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - 
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - Spark properties used, including those specified through
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - --conf and those from the properties file null:
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - (spark.master,spark://spark:7077)
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - 
[2022-02-22 02:16:32,129] {spark_submit.py:488} INFO - 
[2022-02-22 02:16:32,186] {spark_submit.py:488} INFO - Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:972)
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:238)
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:898)
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
[2022-02-22 02:16:32,187] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2022-02-22 02:16:32,215] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 420, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master 172.20.0.9:7077 --conf spark.master=spark://spark:7077 --name Spark book count --verbose /usr/local/spark/app/spark-book-count.py /usr/local/spark/data/book.txt. Error code is: 1.
[2022-02-22 02:16:32,226] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-book-count, task_id=spark_job, execution_date=20220222T021628, start_date=20220222T021629, end_date=20220222T021632
[2022-02-22 02:16:32,248] {standard_task_runner.py:92} ERROR - Failed to execute job 2 for task spark_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 420, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master 172.20.0.9:7077 --conf spark.master=spark://spark:7077 --name Spark book count --verbose /usr/local/spark/app/spark-book-count.py /usr/local/spark/data/book.txt. Error code is: 1.
[2022-02-22 02:16:32,293] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-22 02:16:32,333] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
